# Generated by Django 5.0 on 2023-12-31 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Artist_Name', models.AutoField(primary_key=True, serialize=False)),
                ('Song', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_name', models.AutoField(primary_key=True, serialize=False)),
                ('Artist', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='duration',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Song_Name', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='date_added',
            fields=[
                ('artist_name', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateField()),
                ('albums_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.albums')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.duration')),
            ],
            options={
                'verbose_name_plural': 'Date Added',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='song_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.duration'),
        ),
        migrations.AddField(
            model_name='albums',
            name='Artist_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.title'),
        ),
    ]
