# Generated by Django 5.0 on 2023-12-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_Name',
            new_name='Artist_ID',
        ),
        migrations.AddField(
            model_name='artist',
            name='Artist_ScreenName',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
