# Generated by Django 5.0 on 2023-12-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_albums_created_at_remove_albums_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='Songs_artist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
