# Generated by Django 5.0 on 2023-12-31 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_artist_name_artist_artist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='Artist_Name',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='id',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='song_name',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='albums',
            name='MusicAlbumsName_ID',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albums',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_ScreenName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='albums',
            name='song_Name',
            field=models.CharField(default='Default Value', max_length=255),
        ),
    ]
