# Generated by Django 5.0 on 2023-12-31 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_albums_artist_name_remove_albums_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='song_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
