# Generated by Django 5.0 on 2023-12-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_albums_songs_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='song_name',
            new_name='song_number',
        ),
    ]
