# Generated by Django 5.0 on 2023-12-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_rename_song_name_title_song_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='Artist_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.title'),
        ),
    ]
