# Generated by Django 5.0 on 2023-12-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_albums_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_added',
            old_name='artist_name',
            new_name='id',
        ),
    ]
