# Generated by Django 5.0 on 2023-12-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_rename_artist_name_date_added_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_added',
            old_name='albums_name',
            new_name='albums',
        ),
    ]
