# Generated by Django 5.0 on 2023-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_albums_artist_name_alter_albums_songs_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_Name',
            new_name='Artist_ID',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='Songs_artist',
        ),
        migrations.RemoveField(
            model_name='date_added',
            name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='ArtistName',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
