# Generated by Django 5.0 on 2023-12-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_rename_albums_date_added_albums_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='MusicAlbumsName_ID',
        ),
        migrations.AddField(
            model_name='albums',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
