# Generated by Django 5.0 on 2023-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_rename_artist_name_artist_artist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration',
            old_name='Song_Name',
            new_name='Song_ID',
        ),
        migrations.AddField(
            model_name='duration',
            name='artist_Names',
            field=models.FileField(default=60, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
