# Generated by Django 5.0 on 2023-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_rename_song_name_duration_song_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Art_name',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
