# Generated by Django 5.0 on 2023-12-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_artist_art_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='song_name',
            new_name='song_Name',
        ),
        migrations.AddField(
            model_name='albums',
            name='Songs_artist',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
