# Generated by Django 5.0 on 2023-12-31 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_rename_song_name_albums_song_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_added',
            old_name='artist_name',
            new_name='artistID',
        ),
        migrations.AddField(
            model_name='date_added',
            name='song',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='record.duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albums',
            name='song_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
