# Generated by Django 5.0 on 2023-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_rename_artist_name_date_added_artistid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='Artist_Name',
            new_name='ArtistID',
        ),
        migrations.AddField(
            model_name='albums',
            name='Artist_name',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
