# Generated by Django 5.0 on 2023-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_rename_artist_name_albums_artistid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Art_name',
            new_name='Artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='ArtistName',
        ),
        migrations.AlterField(
            model_name='albums',
            name='song_Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
