# Generated by Django 5.0 on 2023-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_rename_art_name_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_added',
            name='song',
            field=models.CharField(max_length=255),
        ),
    ]
