# Generated by Django 5.0 on 2023-12-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_alter_date_added_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='Artist_name',
        ),
        migrations.AlterField(
            model_name='date_added',
            name='albums_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='duration',
            name='Duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='duration',
            name='artist_Names',
            field=models.CharField(max_length=255),
        ),
    ]
