# Generated by Django 5.0 on 2023-12-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_remove_albums_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_added',
            name='artistNames',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
