# Generated by Django 5.0 on 2023-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_date_added_artistnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='ArtistsName',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
