# Generated by Django 5.0 on 2023-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_albums_artistsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='artistss',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
