# Generated by Django 5.0 on 2023-12-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_albums_artistss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='artistss',
            new_name='NameArtist',
        ),
    ]
