# Generated by Django 5.0 on 2023-12-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_duration_namesartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='ARTistName',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
