# Generated by Django 5.0 on 2023-12-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0022_date_added_albumsartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nameofartist',
            field=models.CharField(default=60, max_length=255),
            preserve_default=False,
        ),
    ]
