# Generated by Django 5.0 on 2024-01-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0024_remove_albums_artistsname_remove_albums_nameartist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_added',
            name='artistNames',
        ),
    ]
