# Generated by Django 5.0 on 2024-01-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0025_remove_date_added_artistnames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date_added',
            options={},
        ),
    ]
